config/routes.rb
Rails.application.routes.draw do
  root "quizzes#index"
  resources :quizzes do
    resources :connections_round
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :rounds
  validates :name, presence: true
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :quiz
end

app/models/rounds/connecting_wall_round.rb
class ConnectingWallRound < Round
end

app/models/rounds/connections_round.rb
class ConnectionsRound < Round
end

app/models/rounds/missing_vowels_round.rb
class MissingVowelsRound < Round
end

app/models/rounds/sequences_round.rb
class SequencesRound < Round
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/connections_round_controller.rb
class ConnectionsRoundController < ApplicationController
  def new
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def index
    @quizzes = Quiz.all
  end

  def new
    @quiz = Quiz.new
  end

  def create
    @quiz = Quiz.new(quiz_params)

    if @quiz.save
      redirect_to new_quiz_connections_round_path(@quiz)
    else
      render :new
    end
  end

  private

  def quiz_params
    params.require(:quiz).permit(:name, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def symbols
    ['Two Reeds', 'Lion', 'Twisted Flax', 'Horned Viper', 'Water', 'Eye of Horus']
  end

  def remove_spaces(name)
    name.gsub(/\s/, '')
  end
end

app/views/application/_banner.html.erb
<div class="banner d-flex align-items-center">
  <%= link_to "InliCinnict", root_path, class: "h1 p-5" %>
</div>

app/views/connections_round/_question.html.erb
<div class="card">
  <div class="card-header" id="heading<%= remove_spaces id %>">
    <h2 class="mb-0">
      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#Collapse<%= remove_spaces id %>" aria-expanded="true" aria-controls="#Collapse<%= remove_spaces id %>">
        <%= id %>
      </button>
    </h2>
  </div>
  <div id="Collapse<%= remove_spaces id %>" class="collapse" aria-labelledby="heading<%= remove_spaces id %>" data-parent="#connectingRoundQuestions">
    <div class="card-body">
      One day you will be able to create your question here
    </div>
  </div>
</div>

app/views/connections_round/new.html.erb
<h1>Add questions for the connecting round</h1>

<div class="accordion" id="connectingRoundQuestions">
  <% symbols.each do |i| %>
    <%= render "question", id: i %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Connect</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render "banner" %>
<div class="px-5 pt-2">
  <%= yield %>
</div>
</body>
</html>

app/views/quizzes/_show.html.erb
<div class="card my-2">
  <div class="card-content">
    <div class="grid">
      <div class="row no-gutters">
        <div class="col-8">
          <h3><%= quiz.name %></h3>
          <h5>By <%= quiz.author %></h5>
        </div>
        <div class="col d-flex justify-content-end align-items-center">
          <%= link_to "Play", quizzes_path, class: "btn btn-primary" %>
          <%= link_to "Leaderboard", quizzes_path, class: "btn btn-primary" %>
          <%= link_to "Edit", quizzes_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quizzes/index.html.erb
<h1>Quizzes!</h1>

<%= link_to "Create a quiz", new_quiz_path, class: "btn btn-primary" %>

<h2>All quizzes</h2>
<% if @quizzes.length == 0 then %>
  Nobody has made any quizzes yet. You can <%= link_to "create a quiz", new_quiz_path %> yourself.
<% end %>
<% @quizzes.each do |quiz| %>
  <%= render "show", quiz: quiz %>
<% end %>

app/views/quizzes/new.html.erb
<h1>Create a quiz</h1>

<%= form_with model: @quiz do |form| %>
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div class="form-group">
    <%= form.label :author %><br>
    <%= form.text_field :author %><br>
  </div>

  <div>
    <%= form.submit "Next" %>
  </div>
<% end %>